version: '3'

services:
  arkitektum.orden:
    image: arkitektum.orden
    build:
      context: .
      dockerfile: Arkitektum.Orden/Dockerfile
  db: 
    image: postgres 
    environment: 
      POSTGRES_PASSWORD: example 
    ports: 
      - 5432:5432 
  adminer: 
    image: adminer 
    ports: 
      - 8080:8080 