//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkitektum.Orden.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkitektum.Orden.Models.ModelsResource", typeof(ModelsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgjengelighet for allmennheten.
        /// </summary>
        public static string AccessRight {
            get {
                return ResourceManager.GetString("AccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årlig kostnad.
        /// </summary>
        public static string AnnualFee {
            get {
                return ResourceManager.GetString("AnnualFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjon.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjoner.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataplassering.
        /// </summary>
        public static string DataLocation {
            get {
                return ResourceManager.GetString("DataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett.
        /// </summary>
        public static string Datasets {
            get {
                return ResourceManager.GetString("Datasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjonselementer.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har masterdata.
        /// </summary>
        public static string HasMasterData {
            get {
                return ResourceManager.GetString("HasMasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har personopplysninger.
        /// </summary>
        public static string HasPersonalData {
            get {
                return ResourceManager.GetString("HasPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har sensitive personopplysninger.
        /// </summary>
        public static string HasSensitivePersonalData {
            get {
                return ResourceManager.GetString("HasSensitivePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driftsplassering.
        /// </summary>
        public static string HostingLocation {
            get {
                return ResourceManager.GetString("HostingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driftsleverandør.
        /// </summary>
        public static string HostingVendor {
            get {
                return ResourceManager.GetString("HostingVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innkjøpskostnad.
        /// </summary>
        public static string InitialCost {
            get {
                return ResourceManager.GetString("InitialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innsikt.
        /// </summary>
        public static string Insight {
            get {
                return ResourceManager.GetString("Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovhjemler.
        /// </summary>
        public static string LawReferences {
            get {
                return ResourceManager.GetString("LawReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasjonal felleskomponent.
        /// </summary>
        public static string NationalComponent {
            get {
                return ResourceManager.GetString("NationalComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasjonale felleskomponenter.
        /// </summary>
        public static string NationalComponents {
            get {
                return ResourceManager.GetString("NationalComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke offentlige data.
        /// </summary>
        public static string NonPublicData {
            get {
                return ResourceManager.GetString("NonPublicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall brukere.
        /// </summary>
        public static string NumberOfUsers {
            get {
                return ResourceManager.GetString("NumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer.
        /// </summary>
        public static string OrganizationNumber {
            get {
                return ResourceManager.GetString("OrganizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjoner og rettigheter.
        /// </summary>
        public static string OrganizationRoles {
            get {
                return ResourceManager.GetString("OrganizationRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjoner.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offentlige data.
        /// </summary>
        public static string PublicData {
            get {
                return ResourceManager.GetString("PublicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisert til felles datakatalog.
        /// </summary>
        public static string PublishedToSharedDataCatalog {
            get {
                return ResourceManager.GetString("PublishedToSharedDataCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husk pålogging.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data med  begrenset tilgang.
        /// </summary>
        public static string RestrictedData {
            get {
                return ResourceManager.GetString("RestrictedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenesteområde.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenesteområder.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemansvarlig.
        /// </summary>
        public static string SystemOwner {
            get {
                return ResourceManager.GetString("SystemOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverandør.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverandørnavn.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjon.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
