//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkitektum.Orden.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkitektum.Orden.Models.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgang avvist.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har ikke tilgang til denne ressursen. Ta kontakt med systemansvarlig dersom dette er feil. .
        /// </summary>
        public static string AccessDeniedExplanation {
            get {
                return ResourceManager.GetString("AccessDeniedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du må velge en leverandør fra listen eller skrive inn navn på en ny leverandør..
        /// </summary>
        public static string ApplicationCreateModelVendorNotDefined {
            get {
                return ResourceManager.GetString("ApplicationCreateModelVendorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felles applikasjonsregister.
        /// </summary>
        public static string AppRegistry {
            get {
                return ResourceManager.GetString("AppRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send inn forslag.
        /// </summary>
        public static string AppRegistrySubmitSuggestion {
            get {
                return ResourceManager.GetString("AppRegistrySubmitSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send inn.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Du kan nå logge på Orden i eget hus&lt;/h4&gt;
        ///&lt;p&gt;For å komme igang må du &lt;a href=&quot;{0}&quot;&gt;aktivere&lt;/a&gt; kontoen din.&lt;/p&gt;
        ///&lt;p&gt;Følg lenken for å aktivere kontoen og registrere et nytt passord&lt;/p&gt;
        ///&lt;p&gt;Kontoen må aktiveres innen 24 timer fra du mottok denne eposten.&lt;/p&gt;.
        /// </summary>
        public static string EmailConfirmationBody {
            get {
                return ResourceManager.GetString("EmailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din brukerkonto hos Orden i eget hus er nå opprettet.
        /// </summary>
        public static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjonen ble send inn til felles applikasjonsregister..
        /// </summary>
        public static string FlashApplicationSubmittedToAppRegistry {
            get {
                return ResourceManager.GetString("FlashApplicationSubmittedToAppRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjonen ble oppdatert..
        /// </summary>
        public static string FlashApplicationUpdated {
            get {
                return ResourceManager.GetString("FlashApplicationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glemt passord?.
        /// </summary>
        public static string ForgotPasswordHeader {
            get {
                return ResourceManager.GetString("ForgotPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn din epostadresse for å sette et nytt passord. Du vil motta en epost med instruksjoner for å lage et nytt passord..
        /// </summary>
        public static string ForgotPasswordHelpText {
            get {
                return ResourceManager.GetString("ForgotPasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er du sikker på at du vil slette dette elementet?.
        /// </summary>
        public static string HelpTextConfirmDeleteItem {
            get {
                return ResourceManager.GetString("HelpTextConfirmDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skytjeneste.
        /// </summary>
        public static string HostingLocationCloud {
            get {
                return ResourceManager.GetString("HostingLocationCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstern server.
        /// </summary>
        public static string HostingLocationExternalServer {
            get {
                return ResourceManager.GetString("HostingLocationExternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal server.
        /// </summary>
        public static string HostingLocationLocalServer {
            get {
                return ResourceManager.GetString("HostingLocationLocalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversikt over kostnader til applikasjoner.
        /// </summary>
        public static string InsightsApplicationCostsHeader {
            get {
                return ResourceManager.GetString("InsightsApplicationCostsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett med personopplysninger.
        /// </summary>
        public static string InsightsDatasetPrivacyHeader {
            get {
                return ResourceManager.GetString("InsightsDatasetPrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruk av felleskomponenter.
        /// </summary>
        public static string InsightsNationalComponentsUsageHeader {
            get {
                return ResourceManager.GetString("InsightsNationalComponentsUsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbake til liste.
        /// </summary>
        public static string LinkBackToList {
            get {
                return ResourceManager.GetString("LinkBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis detaljer.
        /// </summary>
        public static string LinkDetails {
            get {
                return ResourceManager.GetString("LinkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glemt passord?.
        /// </summary>
        public static string LoginForgotPasswordLink {
            get {
                return ResourceManager.GetString("LoginForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrer ny nasjonal felleskomponent.
        /// </summary>
        public static string NationalComponentCreateNew {
            get {
                return ResourceManager.GetString("NationalComponentCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett nytt tjenesteområde.
        /// </summary>
        public static string SectorCreateNew {
            get {
                return ResourceManager.GetString("SectorCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger tjenesteområde.
        /// </summary>
        public static string SectorHeaderEdit {
            get {
                return ResourceManager.GetString("SectorHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenesteområder.
        /// </summary>
        public static string SectorHeaderIndex {
            get {
                return ResourceManager.GetString("SectorHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Velg driftsplassering fra listen - .
        /// </summary>
        public static string SelectHostingLocationFromList {
            get {
                return ResourceManager.GetString("SelectHostingLocationFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Velg leverandør fra listen -.
        /// </summary>
        public static string SelectVendorFromList {
            get {
                return ResourceManager.GetString("SelectVendorFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitiv.
        /// </summary>
        public static string SensitivePersonalDataBadgeText {
            get {
                return ResourceManager.GetString("SensitivePersonalDataBadgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send inn forslag til felles applikasjonsregister.
        /// </summary>
        public static string SubmitApplicationToAppRegistry {
            get {
                return ResourceManager.GetString("SubmitApplicationToAppRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemansvarlig.
        /// </summary>
        public static string SuperUser {
            get {
                return ResourceManager.GetString("SuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukeren ble opprettet og epost med aktiveringslenke er sendt..
        /// </summary>
        public static string UserControllerStatusMessageCreatedUser {
            get {
                return ResourceManager.GetString("UserControllerStatusMessageCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett ny bruker.
        /// </summary>
        public static string UserHeaderCreateNew {
            get {
                return ResourceManager.GetString("UserHeaderCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett bruker.
        /// </summary>
        public static string UserHeaderDelete {
            get {
                return ResourceManager.GetString("UserHeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukere.
        /// </summary>
        public static string UserHeaderList {
            get {
                return ResourceManager.GetString("UserHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg leverandør fra listen eller opprett ny leverandør nedenfor..
        /// </summary>
        public static string VendorHelp {
            get {
                return ResourceManager.GetString("VendorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn navn på leverandør dersom du ønsker å opprette en ny leverandør..
        /// </summary>
        public static string VendorNameHelp {
            get {
                return ResourceManager.GetString("VendorNameHelp", resourceCulture);
            }
        }
    }
}
